// Why a standalone file: the main tsconfig cannot import the CLI project, but
// AppImage direct launches need a conservative allow-list before bypassing the
// GUI startup, so this list is hand-copied from the CLI's top-level verbs.
// Kept in parity by src/cli/appimage-cli-command-names-parity.test.ts (run from
// the CLI side, for the same cross-project-import reason). Split out of
// appimage-cli-redirect.ts, which references Electron's `process.resourcesPath`
// global, so that parity test's tsconfig.cli.json listing has no imports and
// pulls in nothing else.
export const APPIMAGE_CLI_COMMAND_NAMES = [
  'account',
  'agent',
  'agent-context',
  'agents',
  'artifacts',
  'automations',
  'back',
  'capture',
  'check',
  'claude-teams',
  'clear',
  'click',
  'clipboard',
  'computer',
  'console',
  'cookie',
  'dblclick',
  'diagnostics',
  'dialog',
  'download',
  'drag',
  'emulator',
  'environment',
  'eval',
  'exec',
  'file',
  'fill',
  'find',
  'focus',
  'forward',
  'full-screenshot',
  'geolocation',
  'get',
  'goto',
  'highlight',
  'hover',
  'inserttext',
  'intercept',
  'is',
  'keypress',
  'lane',
  'linear',
  'mouse',
  'network',
  'open',
  'orchestration',
  'pdf',
  'project',
  'reload',
  'repo',
  'screenshot',
  'scroll',
  'scrollintoview',
  'select',
  'select-all',
  'serve',
  'set',
  'skills',
  'snapshot',
  'status',
  'storage',
  'tab',
  'terminal',
  'type',
  'uncheck',
  'upload',
  'viewport',
  'vm',
  'wait',
  'worktree'
]
