// Ruling 28 Addendum 1(t): the CLI's flag grammar (which flags consume no value) as an
// array literal, one name per line — args.ts's data-as-string re-encoding of this list evaded
// the max-lines cap on the CONTROL rather than meeting it by splitting the file (Gate 1/D-5).
// Byte-identical to the prior BOOLEAN_FLAG_NAMES set — 56 names — asserted by the existing
// flag-grammar test.
export const BOOLEAN_FLAG_NAMES = [
  'accept-legacy',
  'accept-unverified-platform',
  'acknowledge-gate',
  'all',
  'all-hosts',
  'attachments',
  'cancel',
  'children',
  'clear',
  'comments',
  'connect',
  'current',
  'deep',
  'drain',
  'dry-run',
  'enter',
  'focus',
  'force',
  'full',
  'help',
  'inject',
  'include-archived',
  'include-quarantined',
  'include-visual-layouts',
  'interrupt',
  'json',
  'leave',
  'lift',
  'local',
  'messages',
  'me',
  'mobile',
  'mobile-pairing',
  'new',
  'no-derived',
  'no-pairing',
  'outbox',
  'parent-current',
  'provision',
  'ready',
  'recipe-json',
  'relations',
  'reinstall',
  'restore-window',
  'return-preamble',
  'run-hooks',
  'sensitive',
  'show-profile',
  'staged',
  'tab',
  'tasks',
  'text-stdin',
  'unread',
  'value-stdin',
  'wait',
  'yes'
]
